<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14.0</LangVersion>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PCCExecutive.App/PCCExecutive.App.csproj" />
    <ProjectReference Include="../../src/PCCExecutive.Domain/PCCExecutive.Domain.csproj" />
    <ProjectReference Include="../../src/PCCExecutive.Application/PCCExecutive.Application.csproj" />
    <ProjectReference Include="../../src/PCCExecutive.Browser/PCCExecutive.Browser.csproj" />
    <ProjectReference Include="../../src/PCCExecutive.Infrastructure/PCCExecutive.Infrastructure.csproj" />
  </ItemGroup>
</Project>
